### ISSUE TITLE
general section: TotalUnique is not handled

### ISSUE THREAD

**Issue by lelutin** [AaronVanGeffen/AwstatsParser#2]
Hey there,

pretty neat script. I've done a test with a data set from a bunch of domains that are now merged. All seems ok for now, except for the unique visitors.. it seems to be handled in a weird way:

sometimes I get a somewhat sensible value, some other times I get a very low value. I haven't dug too far in the code yet but I suspect that only the last seen value is saved.

I'm not too sure how this should be managed without the log files. we probably can't recalculate this accurately because we're working only with processed data. but having an arbitrary value for this is a little unsettling.

**Comment by AndreiGhitan** [comment]
I just tried using your tool, great tool btw. 

One bug I came across is that after I merged 2 log files, in awstats it displays the following error message:

Error: History file '/home/usr/tmp/awstats/awstats012017.mydomain.com.txt' is to old (version '0'). This version of AWStats is not compatible with very old history files. Remove this history file or use first a previous AWStats version to migrate it from command line with command: awstats.pl -migrate="/home/usr/tmp/awstats/awstats012017.proxyape.com.txt".

And in the file the first 2 lines ar giving me this output:

Warning: A non-numeric value encountered in /Users/Zamolxis/Downloads/Awmerge/src/AaronVanGeffen/AwstatsParser/AwstatsMerger.php on line 272

Warning: A non-numeric value encountered in /Users/Zamolxis/Downloads/Awmerge/src/AaronVanGeffen/AwstatsParser/AwstatsMerger.php on line 272
AWSTATS DATA FILE 6.9 (build 1.925)

Is there any way you could update it?

Thank you for building this tool!

**Comment by AaronVanGeffen** [comment]
Unfortunately, the values for unique visitors cannot be recalculated from the aggregated data provided in the Awstats log files. The most we could do is take the highest of the values provided in both input files. To me, that isn't necessarily a better solution, however.

If you do prefer the workaround described above, make sure your main input file is the first argument to the script (or indeed the file instantiating the class). The values should not be overwritten.
